baseURL = "/"
languageCode = "en-us"
title = "gbdq.kz"
theme = "cactus"
copyright = "gbdq.kz"
disqusShortname = "gbdq"
# googleAnalytics = "UA-1234-5"


summaryLength = 50

[[menu.main]]
name = "posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "about"
url = "/about"
weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "Welcome! This page serves as an overview of me and my online presence."
  mainSection = "posts" 
  mainSectionTitle = "posts" 
  showAllPostsOnHomePage = false 
  postsOnHomePage = 10 
  tagsOverview = false 
  showProjectsList = false
  projectsUrl = "https://github.com/gabdylgaziz" 

  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default


  [[params.social]]
    name = "github"
    link = "https://github.com/gabdylgaziz"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/gabdylgaziz-zhagypar/"
  [[params.social]]
    name = "email"
    link = "gzagipar@gmail.com" 
